apiVersion: batch/v1
kind: Job
metadata:
  name: grabber
spec:
  template:
    spec:
      nodeName: gabbro
      restartPolicy: Never
      volumes:
      - name: proc-dir
        hostPath:
          path: /proc
          type: Directory
      - name: cgroup-dir
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - name: output
        hostPath:
          path: /mnt/kubernetes/cgroup_out/prometheus
          type: Directory
      containers:
      - name: mem-grabber
        image: gabbro:30500/grabber:latest
        imagePullPolicy: Never
        command: ["metrics-grabber", "--pid", "$(PID)", "--out", "$(OUTPUT)", "--mtype", "mem", "--freq", "3", "--iter", "10000"]
        env:
        - name: PID
          value: "2632"
        - name: OUTPUT
          value: app
        volumeMounts:
        - mountPath: /tmp/proc
          name: proc-dir
        - mountPath: /tmp/cgroup
          name: cgroup-dir
        - mountPath: /output
          name: output
