## Copyright 2022 Carol Hsu
## 
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
## 
##     http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: colibri-job
  namespace: colibri
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: colibri-apiserver-post-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: colibri-apiserver-post
subjects:
- kind: ServiceAccount
  name: colibri-job
  namespace: colibri
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: colibri-apiserver-post
rules:
- apiGroups:
  - ""
  resources: ["services/proxy"]
  verbs: ["create"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: colibri-job
  namespace: colibri
spec:
  template:
    spec:
      nodeName: gabbro
      serviceAccountName: colibri-job
      restartPolicy: Never
      volumes:
      - name: proc-dir
        hostPath:
          path: /proc
          type: Directory
      - name: cgroup-dir
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - name: output
        hostPath:
          path: OUTPUT_DIR
          type: Directory
      containers:
      - name: get-all-metrics
        image: colibri:latest
        imagePullPolicy: Never
        command: ["colibri", "--pid", "$(PID)", "--freq", "25", "--out", "$(OUTPUT)", "--iter", "480", "--mtype", "all"]
        env:
        - name: PID
          value: "APP_PID"
        - name: OUTPUT
          value: "api:NAMESPACE.PODNAME.APP_PID"
        volumeMounts:
        - mountPath: /tmp/proc
          name: proc-dir
        - mountPath: /tmp/cgroup
          name: cgroup-dir
        - mountPath: /output
          name: output
